### ISSUE TITLE
[설계] 엔티티 설계 1차

### ISSUE THREAD

**Issue by Ujoonnee** [geshphan/gsp-back#16]
회원, Todo 기능에 필요한 엔티티 설계

확장성에 대해서는 적극적으로 고려하지 않고, 최초 계획인 회원, Todo, 태그 기능 이후 추가적인 계획 발생 시 재설계 예정

요청, 응답 데이터 회의 후 설계 시작 예정

Refer discussion https://github.com/geshphan/Wiki/discussions/4

**Comment by Ujoonnee** [comment]
회원,  Todo 기능에 필요한 엔티티 설계

확장성에 대해서는 적극적으로 고려하지 않고, 최초 계획인 회원, Todo, 태그 기능 이후 추가적인 계획 발생 시 재설계 예정

**Comment by Ooyd** [comment]
**Todo**
|컬럼명|타입|역할|
|:---:|:---:|:---:|
|todoId|INT(PK)|고유 식별자|
|memberId|INT(FK)|Member 식별자(특정 고유 pk값은 int)|
|title|VARCHAR|제목|
|description|VARCHAR|내용|
|status|VARCHAR|TODO상태(예:진행 중, 완료, 보류)|
|createdTime|DATETIME|TODO생성일|
|dueDate|DATETIME|TODO마감일|
|isDeleted|boolean|삭제여부|

**Tag**
|컬럼명|타입|역할|
|:---:|:---:|:---:|
|tagId|INT(PK)|고유 식별자|
|name|VARCHAR|태그 명|

**TodoTagRelation**
|컬럼명|타입|역할|
|:---:|:---:|:---:|
|mappingId|INT(PK)|고유 식별자|
|todoId|INT(FK)|todo 식별자|
|tagId|INT(FK)|tag 식별자|

**Comment by Ujoonnee** [comment]
바로 적용하기에도 충분한 테이블 관계라고 생각합니다.

몇 가지 생각해볼 수 있는 점을 이야기해 보자면,
1. Todo 테이블의 값이 수정될 경우, 수정자와 수정 일시에 대한 정보는 관리하지 않아도 될까요?
    - 만약 해야 한다면, 예를 들어 Todo 테이블에서 최종 수정 정보를 관리할지, 로그 테이블을 만들어 매 변경을 기록할지.
2. Todo - Tag 를 매핑하는 테이블을 만들어서 관리하고 있는데, 단순히 Tag 테이블에 Todo의 기본 키를 외래 키로 받아 연관관계를 설정하는 것은 어떨까요?

위 내용에 대한 의견이 궁금합니다.

**Comment by Ooyd** [comment]
1. 해당부분은 우선 기본적으로 들어갈 기능들을 우선적으로 고려했기때문에, 세부적인 부분은 파악을 못했습니다. 하지만 수정자 같은경우 해당 테이블은 회원의pk값을 참조하기에 다른 수정자가 고려될 부분이 없다 생각합니다. 그리고 수정일시 같은경우 말씀하신대로 관리가 필요한 부분이라 생각됩니다. 
제 의견은 해당 Todo테이블의 로그테이블을 만들어 시간 및 Todo 내용을 따로 관리하는게 좋을것같습니다.
2. 태그와 Todo가 다대일의 관계라면 Todo의 PK키를 외래키로 받아서 구상하는것도 좋을것같습니다. 그렇지만 제 생각은 Todo와 해시태그는 특성상 다대다 관계가 될 여지가 있다고 판단되고 태그테이블 자체가 특정fk에 묶이는게 좋지않다라고 생각이 들었습니다.

**Comment by Ujoonnee** [comment]
> 제 생각은 Todo와 해시태그는 특성상 다대다 관계가 될 여지가 있다고 판단되고

각 Todo 별로 이륾만 같은 태그가 아니라 테이블에서 관리하는 태그를 매핑시켜 등록하겠다 라는 뜻으로 이해했는데요,

태그를 단순히 Todo에서 등록한 정보가 아니라 태그에서 필요한 정보가 있어서 그렇게 판단했을 거라 생각하겠습니다.

구성하신 연관관계로 Todo - Tag 매핑테이블, Tag 테이블을 제외한 기능은 개발이 바로 가능할 것으로 보입니다. Project에서 일정 한번 확인해 주시고 바로 작업 시작해 주세요!
